### PR TITLE
use absl for int128

### PR DESCRIPTION
**Pull request by filimonov**
Backport 
https://github.com/artpaul/clickhouse-cpp/pull/119

See
https://github.com/artpaul/clickhouse-cpp/issues/113
https://github.com/artpaul/clickhouse-cpp/issues/116

### CODE REVIEW

**Comment by azat** [comment]
@filimonov are you going to finish this?

**Comment by filimonov** [comment]
No :)

I've just make a backport from artpaul repo to expose it here / to sync the projects. 

Have no idea what is broken and how to fix, and i know the code around very badly, feel free to pick it if you want. I guess some tiny efforts are needed to make it work.

**Comment by azat** [comment]
Does absl int128 has some benefits over simply gnu++17?
Requiring absl just for int128 looks a little bit overkill.

**Comment by Dlougach** [comment]
I am a bit concerned about potential ODR problems if someone uses both absl and clickhouse-cpp in their projects.

**Pull request merged**
