### PR TITLE
Ability to build packages (rpm, deb) after build and install

### PR DESCRIPTION
**Pull request by yoori**
Hi guys, great job ! I need your project )

I simple need to build your project into rpm for fix and control binary and source versions of third party libraries in my projects ...
Here, few changes that gave me this ability with next instructions in rpm spec file:

`
%build
%cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX:PATH=/usr \
  -DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=ON -DCMAKE_INSTALL_LIBDIR=%{_lib}
make -j
%install
DESTDIR=%{buildroot}/ make install INSTALL_PATH=%{buildroot}/
`

Thank you.

### CODE REVIEW

**Comment by Jihadist** [comment]
Why not to use cpack?

**Comment by yoori** [comment]
Hi,

I don't use cpack for build packages (like much other packagers) by much reasons, for example : "build requires" have different package names and versions on different platforms - and easier to write platform specific spec then write branch for it in CPack syntax.

But all ways require correct "make or cmake install" result - and changes about this step.

Regards, yoori

**Comment by Enmk** [comment]
Hi @yoori kind ping!

**Comment by Enmk** [comment]
Hi @yoori please fix issues discovered by CI/CD so this can be merged

**Comment by Enmk** [comment]
@yoori kind ping

**Pull request closed without merging**
