### PR TITLE
fix:ipv4 column append problem

### PR DESCRIPTION
**Pull request by ghost**
#88 fix:ipv4 column append problem.author:  BozaB.

### CODE REVIEW

**Comment by BozaB** [comment]
Hellozhuzhu, thank you! :)

**Comment by filimonov** [comment]
Great, can you also add the problematic ip to the test?

https://github.com/ClickHouse/clickhouse-cpp/blob/1415b5936a2ac2f084850b09057e05fb5798b2f1/tests/simple/main.cpp#L444

**Comment by hellozhuzhu** [comment]
Of course.

**Review by Enmk — CHANGES_REQUESTED** [review]
Please sign CLA and write some unit tests, `simple/main.cpp` is not built/run in CI/CD

**Pull request closed without merging**
