### PR TITLE
add parameterized syntax, just syntax-sugar

### PR DESCRIPTION
**Pull request by 1261385937**
Now clickhouse-cpp supports parameterized syntax, and the placeholder should be ? .
It is just syntax-sugar, all replacing happens on the client side

Any document about clickhouse-server prepare statement? 
@Enmk

### CODE REVIEW

**Comment by 1261385937** [comment]
#153

**Comment by Enmk** [comment]
Closing to re-open and re-trigger CI/CD

**Comment by Enmk** [comment]
I suggest utilizing existing CH features for that:
https://clickhouse.com/docs/en/sql-reference/syntax#defining-and-using-query-parameters
For users that means they'd have to use `{pid:UInt16}` syntax.

For developers, that means we'd have to either
- prepend query with multiple `SET` queries, which I dislike.
- or update `TCPHandler` to take parameters from settings and apply that to query context (pretty much the same way it is done in HTTP handler)

Notes to myself on how to implement later on CH side:
src/Parsers/ASTSetQuery.h:10 `constexpr char QUERY_PARAMETER_NAME_PREFIX[] = "param_";`
Context::setQueryParameter() with those in TCPHandler.cpp
src/Interpreters/executeQuery.cpp `executeQuery` seems to be handling query parameters just fine.

**Comment by 1261385937** [comment]
ok

**Pull request closed without merging**
