### PR TITLE
Add support for MSVC

### LINKED ISSUE #127: 'Failed to connect' exception using MSVC
Hello,

I was using MSVC to build clickhousecpp (version 2.0.0) on Windows, and the static library was generated successfully. However, an exception of ```failed to connect``` occurred when I run the **simple-test** project. There is a clickhouse server running on my localhost, exposing the 9000 port. I test the connection with python ```clickhouse_driver``` and everything is ok.

By the way, I encountered a problem with ```signbit: ambiguous call to overloaded function``` when I was building the clickhousecpp library. The problem was solved according to [#100](https://github.com/ClickHouse/clickhouse-cpp/issues/100), and I don't know whether it is an official solution.

Is there any idea of this issue?

Thanks

### LINKED ISSUE #130: Add github actions for windows / MSVC build

### PR DESCRIPTION
**Pull request by filimonov**
* github action for msvc added. Closes #130
* there is an issue with dynamic linking & DLL paths when compiling tests. I've switched tests to static linking
* added tls offoader proxy for windows tests, mimicking local clickhouse by tunneling the queries to a cloud instance of clickhouse
* get proper status codes via WSAGetLastError for windows, fixes #127 

Known issues:
- no support for secure connections (need to reimplement secure_socket with sspi.h and other windows thing). Maybe can work with openssl (not tested).
- there are some warnings at compile time

### CODE REVIEW

**Comment by filimonov** [comment]
Failure on clang: https://bugs.llvm.org/show_bug.cgi?id=16404 (happens only with static linking), looks caused by `__builtin_mul_overflow` call

**Comment by filimonov** [comment]
```
 D:\a\clickhouse-cpp\clickhouse-cpp\ut\columns_ut.cpp(461): error: Expected equality of these values:
  0xffffffffffffffffll
    Which is: -1
  col->At(1)
    Which is: 18446744073709551615
``` 
is a real issue?

**Comment by Enmk** [comment]
> ```
>  D:\a\clickhouse-cpp\clickhouse-cpp\ut\columns_ut.cpp(461): error: Expected equality of these values:
>   0xffffffffffffffffll
>     Which is: -1
>   col->At(1)
>     Which is: 18446744073709551615
> ```
> 
> is a real issue?

Just a broken test, fixed

**Review by Enmk — APPROVED** [review]
LGTM

**Pull request merged**
