### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by Enmk**
- attempt to fix 'unresolved external symbol "const clickhouse::ColumnFixedString::`vftable'"' @ string.h/.cpp
- minor test improvement to verify Swap() correctness @ ut/Column_ut.cpp
- exception if SSL wouldn't be configured by configureSSL @ sslsocket.cpp
- removed unused QuerySettings @ query.h

### CODE REVIEW

**Comment by 1261385937** [comment]
Still has unresolved external symbol

**Comment by 1261385937** [comment]
``` c++
1>client_ut.obj : error LNK2001: unresolved external symbol "public: static class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const clickhouse::Query::default_query_id" (?default_query_id@Query@clickhouse@@2V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@B)
1>performance_tests.obj : error LNK2001: unresolved external symbol "public: static class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const clickhouse::Query::default_query_id" (?default_query_id@Query@clickhouse@@2V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@B)
1>roundtrip_column.obj : error LNK2001: unresolved external symbol "public: static class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const clickhouse::Query::default_query_id" (?default_query_id@Query@clickhouse@@2V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@B)
1>columns_ut.obj : error LNK2019: unresolved external symbol "const clickhouse::ColumnFixedString::`vftable'" (??_7ColumnFixedString@clickhouse@@6B@)，function "public: __cdecl clickhouse::ColumnFixedString::ColumnFixedString<class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > >(unsigned __int64,class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > const &)" (??$?0V?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@std@@@ColumnFixedString@clickhouse@@QEAA@_KAEBV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@std@@@Z) quote the symbol
1>D:\contrib\clickhouse-cpp-dll\clickhouse-cpp\sln\ut\Debug\clickhouse-cpp-ut.exe : fatal error LNK1120: two unresolved external symbol
```

**Comment by 1261385937** [comment]
@Enmk  same time online.  zzzz

**Comment by Enmk** [comment]
@1261385937, could you please share the way you build it? I'm thinking about adding another CI/CD workflow variant to speed discovering/fixing such things up.

**Comment by 1261385937** [comment]
> @1261385937, could you please share the way you build it? I'm thinking about adding another CI/CD workflow variant to speed discovering/fixing such things up.

clickhouse/CMakeLists.txt, add  below line:
```cmake
SET (CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS TRUE)
```
ut/CMakeLists.txt, change static to share:
```cmake
TARGET_LINK_LIBRARIES (clickhouse-cpp-ut
    clickhouse-cpp-lib
    gtest-lib
)
```

**Pull request closed without merging**
